/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.2   2020-04-03

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>


#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"

#include <STM32F103_UART.h>
#include "STM32F103_I2C.h"
#include "STM32F103_PWM.h"
#include "STM32F103_VL53L0X.h"
#include "timers.h"
#include "SG90.h"





/* Private typedef */
/* Private define  */
#define USE_CHRONO

#define NB_OF_MEASURES 5

#define VERSION_REQUIRED_MAJOR 1
#define VERSION_REQUIRED_MINOR 0
#define VERSION_REQUIRED_BUILD 2

/* Private macro */
/* Private variables */
 USART_InitTypeDef USART_InitStructure;
 char UART_buffer[200];
 volatile bool print = false, changePos = false;
 float angles[] = {-90.0f, -75.0f, 0.0f, 75.0f, 90.0f};
 volatile float angle = 0.0, deltaTheta = 1.0f;
 volatile int i = 0;

/* Private function prototypes */
/* Private functions */
void initLED(void);
void toggleLED(void);

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

int main(void)
{
  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /* TODO - Add your application code here */

  SystemInit();
  SystemCoreClockUpdate();

  // Configure the SysTick timer to overflow every 1 ms
#ifdef USE_OTHER_I2C
  SysTick_Config(SystemCoreClock / 1000);
#else
  // Configure the SysTick timer to overflow every 1 us
  SysTick_Config(SystemCoreClock / 1000000);
#endif
  initLED();

  //  timerInit(2, 7200, 10000); // 72 MHz / 7200 = 10000 Hz / 10000 = 1 Hz
  timerInit(2, 7200, 250); // 72 MHz / 21600
  timerInterruptEnable(2, TIM_IT_Update);

//  timerInit(3, 400, 3600);
//  PWM_Init(1, (uint16_t) 270, 1);

  ServosInit();
  UART2Init(9600, 0);
  UART2puts("UART2 Initialised..\r\n");

  I2CEnablePeriphClock();

  /*	Official ST API		*/

  VL53L0X_Error Status = VL53L0X_ERROR_NONE;
  VL53L0X_Dev_t MyDevice;
  VL53L0X_Dev_t *pMyDevice = &MyDevice;
  VL53L0X_Version_t                   Version;
  VL53L0X_Version_t                  *pVersion   = &Version;

  int32_t status_int;

// Initialize Comms
  pMyDevice->I2cDevAddr      = 0b0101001;
  pMyDevice->comms_type      =  1;
  pMyDevice->comms_speed_khz =  400;

  /*
   * Disable VL53L0X API logging if you want to run at full speed
   */
#ifdef VL53L0X_LOG_ENABLE
  VL53L0X_trace_config("test.log", TRACE_MODULE_ALL, TRACE_LEVEL_ALL, TRACE_FUNCTION_ALL);
#endif

  /*
   *  Get the version of the VL53L0X API running in the firmware
   */

  if(Status == VL53L0X_ERROR_NONE)
  {
	  status_int = VL53L0X_GetVersion(pVersion);
	  if (status_int != 0)
		  Status = VL53L0X_ERROR_CONTROL_INTERFACE;
  }

  /*
   *  Verify the version of the VL53L0X API running in the firmrware
   */

  if(Status == VL53L0X_ERROR_NONE)
  {
	  if( pVersion->major != VERSION_REQUIRED_MAJOR ||
		  pVersion->minor != VERSION_REQUIRED_MINOR ||
		  pVersion->build != VERSION_REQUIRED_BUILD )
	  {
		  printf("VL53L0X API Version Error: Your firmware has %d.%d.%d (revision %d). This example requires %d.%d.%d.\r\n",
			  (int) pVersion->major, (int) pVersion->minor, (int) pVersion->build, (int) pVersion->revision,
			  VERSION_REQUIRED_MAJOR, VERSION_REQUIRED_MINOR, VERSION_REQUIRED_BUILD);
	  }
  }


  /*	Own implementation		*/
//  UART2puts("Call of VL53L0X_ResetDevice\r\n\t");
//  Status = VL53L0X_ResetDevice(pMyDevice);
//  print_pal_error(Status);

  UART2puts("Call of VL53L0XInit...\r\n");
  if(Status == VL53L0X_ERROR_NONE)
  {
	  Status = VL53L0XInit(pMyDevice, VL53L0X_DEVICEMODE_CONTINUOUS_RANGING);
	//  Status = VL53L0XInit(pMyDevice, VL53L0X_DEVICEMODE_SINGLE_RANGING);
	  print_pal_error(Status);
  }

  uint32_t n = 5;
  uint16_t measures[n], avg;
  if( Status ==  VL53L0X_ERROR_NONE)
  {
	  for(uint8_t i = 0; i < 4; i++)
	  {
		  sprintf(UART_buffer, "Call of VL53L0XGetMeasures (%i/4)\r\n\t", i);
		  UART2puts(UART_buffer);
		  Status = VL53L0XGetMeasures(pMyDevice, measures, &n);
		  print_pal_error(Status);

		  avg = 0;
		  for(uint8_t j = 0; j < n; j++)
		  {
			  avg = avg + measures[j];
		  }
		  avg = (uint16_t) (avg/n);
		  sprintf(UART_buffer, "Average measure: %d mm\r\n", (int) avg);
		  UART2puts(UART_buffer);

		  VL53L0X_PollingDelay(pMyDevice);
		  n = 32;
	  }
  }

  return Status;

}

void TIM2_IRQHandler()
{
	if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET)
	{
		TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
		toggleLED();

		print = true;
//		angle = angles[i++];
		angle = angle + deltaTheta;
		if(abs(angle) > 90)
		{
			deltaTheta = -deltaTheta;
			angle = angle + deltaTheta;
		}
		if(i > 5) i = 0;
	}
}

void initLED()
{
	GPIO_InitTypeDef GPIO_init_struct;
	// Enable clock for GPIOC

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC, ENABLE);

	// Configure PC13 (LED) as push-pull output
	GPIO_init_struct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_init_struct.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_init_struct.GPIO_Pin = GPIO_Pin_13;
	GPIO_Init(GPIOC, &GPIO_init_struct);

}

void toggleLED()
{
	// If led is set we reset it, we set it otherwise
	if(GPIO_ReadOutputDataBit(GPIOC, GPIO_Pin_13))
	{
		GPIO_ResetBits(GPIOC, GPIO_Pin_13);
	}
	else
	{
		GPIO_SetBits(GPIOC, GPIO_Pin_13);
	}
}


/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

